package com.cst338.cst338_project02_group3.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.cst338.cst338_project02_group3.database.DatingAppDatabase;

import java.util.Objects;

@Entity(tableName = DatingAppDatabase.MATCHES_TABLE)
public class Matches {
    @PrimaryKey(autoGenerate = true) // Unique signifier for each match
    private int matchId;

    private int userId1;
    private int userId2;

    // Constructor (autogenerated)
    public Matches(int userId1, int userId2) {
        this.userId1 = userId1;
        this.userId2 = userId2;
    }

    // Equals and HashCode (autogenerated)
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Matches matches = (Matches) o;
        return matchId == matches.matchId && userId1 == matches.userId1 && userId2 == matches.userId2;
    }

    @Override
    public int hashCode() {
        return Objects.hash(matchId, userId1, userId2);
    }

    // Getters and Setters (autogenerated)
    public int getMatchId() {
        return matchId;
    }

    public void setMatchId(int matchId) {
        this.matchId = matchId;
    }

    public int getUserId1() {
        return userId1;
    }

    public void setUserId1(int userId1) {
        this.userId1 = userId1;
    }

    public int getUserId2() {
        return userId2;
    }

    public void setUserId2(int userId2) {
        this.userId2 = userId2;
    }
}
